const BlogPost = [
  {
    img: "/img/blog/hack.png",
    category: ["stripping-and-sealing", "carpet-cleaning"],
    date: "24 Jul, 2019",
    title: "10 Office Cleaning Hacks for an Instant Workspace",
    author: "Chathura Sanka",
    link: "cleaning-hacks",
    path: "/blog/cleaning-hacks",
    shortName: "Cleaning Hacks",
  },
  {
    img: "/img/blog/perth.png",
    category: ["office-cleaning", "pressure-washing"],
    date: "24 Jul, 2019",
    title: "Office Cleaning Perth",
    author: "Chathura Sanka",
    link: "cleaning-perth",
    path: "/blog/why-choose-local-company",
    shortName: "Cleaning Perth",
  },
  {
    img: "/img/blog/why.png",
    category: ["carpet-cleaning", "office-cleaning"],
    date: "24 Jul, 2019",
    title: "Why Choose a Local Cleaning Company Over Big Franchises",
    author: "Chathura Sanka",
    link: "why-choose-local-company",
    path: "/blog/cleaning-perth",
    shortName: "Why Choose Local Company",
  },
  {
    img: "/img/blog/diy.png",
    category: ["carpet-cleaning"],
    date: "15 May, 2025",
    title: "Can DIY Carpet Cleaning Complete with Professional Results?",
    author: "Chathura Sanka",
    link: "diy-carpet-cleaning",
    path: "/blog/diy-carpet-cleaning",
    shortName: "DIY Carpet Cleaning",
  },
  {
    img: "/img/blog/hack.png",
    category: ["carpet-cleaning"],
    date: "15 May, 2025",
    title: "How Professional Carpet Cleaning Saves You Money",
    author: "Chathura Sanka",
    link: "carpet-cleaning-saves-money",
    path: "/blog/carpet-cleaning-saves-money",
    shortName: "Carpet Cleaning Saves Money",
  },
  {
    img: "/img/blog/hack.png",
    category: ["carpet-cleaning"],
    date: "15 May, 2025",
    title: "The Hidden Dangers in Your Carpet",
    author: "Chathura Sanka",
    link: "hidden-dangers-in-your-carpet",
    path: "/blog/hidden-dangers-in-your-carpet",
    shortName: "Hidden Dangers in Your Carpet",
  },
  {
    img: "/img/blog/ocrc.png",
    category: ["office-cleaning"],
    date: "15 May, 2025",
    title: "The Difference Between Deep Cleaning and Regular Cleaning",
    author: "Chathura Sanka",
    link: "difference-between-deep-cleaning-and-regular-cleaning",
    path: "/blog/difference-between-deep-cleaning-and-regular-cleaning",
    shortName: "Cleaning vs Regular Cleaning",
  },
  {
    img: "/img/blog/bcrc.png",
    category: ["office-cleaning"],
    date: "15 May, 2025",
    title: "Office Cleaning vs Residential Cleaning",
    author: "Chathura Sanka",
    link: "office-cleaning-vs-residential-cleaning",
    path: "/blog/office-cleaning-vs-residential-cleaning",
    shortName: "Office vs Residential Cleaning",
  },
  {
    img: "/img/blog/checklist.png",
    category: ["office-cleaning"],
    date: "15 May, 2025",
    title: "Office Cleaning Checklist",
    author: "Chathura Sanka",
    link: "office-cleaning-checklist",
    path: "/blog/office-cleaning-checklist",
    shortName: "Office Cleaning Checklist",
  },
  {
    img: "/img/blog/hos.png",
    category: ["office-cleaning"],
    date: "15 May, 2025",
    title: "How Often Should You Clean Your Office?",
    author: "Chathura Sanka",
    link: "how-often-should-you-clean-your-office",
    path: "/blog/how-often-should-you-clean-your-office",
    shortName: "Clean Your Office",
  },
  {
    img: "/img/blog/hac.png",
    category: ["office-cleaning"],
    date: "15 May, 2025",
    title: "How a Clean & Tidy Workplace Improves Efficiency and Productivity",
    author: "Chathura Sanka",
    link: "how-a-clean-tidy-workplace-improves-efficiency-and-productivity",
    path: "/blog/how-a-clean-tidy-workplace-improves-efficiency-and-productivity",
    shortName: "Clean & Tidy Workplace",
  },
  {
    img: "/img/blog/hack.png",
    category: ["pressure-washing"],

    date: "15 May, 2025",
    title: "Why Regular Pressure Washing is Essential for Property Maintenance",
    author: "Chathura Sanka",
    link: "why-regular-pressure-washing-is-essential-for-property-maintenance",
    path: "/blog/why-regular-pressure-washing-is-essential-for-property-maintenance",
    shortName: "Regular Pressure Washing",
  },
  {
    img: "/img/blog/hack.png",
    category: ["pressure-washing"],
    date: "15 May, 2025",
    author: "Chathura Sanka",
    title: "Top Paver Maintanance Tips",
    link: "top-paver-maintanance-tips",
    path: "/blog/top-paver-maintanance-tips",
    shortName: "Top Paver Maintanance Tips",
  },
  {
    img: "/img/blog/hack.png",
    category: ["pressure-washing"],
    date: "15 May, 2025",
    author: "Chathura Sanka",
    title: "When to Pressure Wash Your Home in Perth",
    link: "when-to-pressure-wash-your-home-in-perth",
    path : "/blog/when-to-pressure-wash-your-home-in-perth",
    shortName: "When to Pressure Wash Your Home",
  },
  {
    img: "/img/blog/hack.png",
    category: ["pressure-washing"],
    date: "15 May, 2025",
    author: "Chathura Sanka",
    title: "Pressure Washing vs Soft Washing",
    link: "pressure-washing-vs-soft-washing",
    path: "/blog/pressure-washing-vs-soft-washing",
    shortName: "Pressure Washing vs Soft Washing",
  },
  {
    img: "/img/blog/hack.png",
    category: ["pressure-washing"],
    date: "15 May, 2025",
    author: "Chathura Sanka",
      title: "Pressure Washing for Businesses",
    link: "pressure-washing-for-businesses",
    path : "/blog/pressure-washing-for-businesses",
    shortName: "Pressure Washing for Businesses",
  },
  {
    img: "/img/blog/hack.png",
    category: ["pressure-washing"],
    date: "15 May, 2025",
    author: "Chathura Sanka",
    title: "How to Keep Your Driveway & Pavers Clean",
    link: "how-to-keep-your-driveway-pavers-clean",
    path : "/blog/how-to-keep-your-driveway-pavers-clean",
    shortName: "Keep Your Driveway & Pavers Clean",
  },
  {
    img: "/img/blog/hack.png",
    category: ["stripping-and-sealing"],
    date: "15 May, 2025",
    author: "Chathura Sanka",
    title: "Bring Back the Shine",
    link: "bring-back-the-shine",
    path : "/blog/bring-back-the-shine",
    shortName: "Bring Back the Shine",
  },
  {
    img: "/img/blog/hack.png",
    category: ["stripping-and-sealing"],
    date: "15 May, 2025",
    author: "Chathura Sanka",
    title: "What is Strip & Seal and Why does Your Floor Need It?",
    link: "what-is-strip-seal-and-why-does-your-floor-need-it",
    path : "/blog/what-is-strip-seal-and-why-does-your-floor-need-it", 
    shortName: "What is Strip & Seal",
  },
  {
    img: "/img/blog/hack.png",
    category: ["stripping-and-sealing"],
    date: "15 May, 2025",
    author: "Chathura Sanka",
    title: "Why Skipping Floor Maintenance Costs You More in the Long Run",
    link: "why-skipping-floor-maintenance-costs-you-more-in-the-long-run",
    path : "/blog/why-skipping-floor-maintenance-costs-you-more-in-the-long-run",
    shortName: "Skipping Floor Maintenance",
  }
];

export default BlogPost;
