name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Match your project

      - name: Install dependencies
        run: npm ci

      - name: Build and export static site
        run: |
          npm run build

      - name: Archive static site
        run: tar -czf static-site.tar.gz dist

      - name: Deploy to EC2 via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.tar.gz"
          target: "~/next-deploy"

      - name: SSH into EC2 and run deploy commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/next-deploy
            tar -xzf app.tar.gz
            npm install --production
            pm2 restart next-app || pm2 start npm --name next-app -- start
